# -*- coding: utf-8 -*-
"""
/***************************************************************************
 dl_infrastructure
                                 A QGIS plugin
 Plugin to download up-to-date files of "Infrastructures électriques au dessus de 5W" from the ANFR site 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-09-11
        copyright            : (C) 2018 by Pluffyz
        email                : none
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load dl_infrastructure class from file dl_infrastructure.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .dl_infrastructure import dl_infrastructure
    return dl_infrastructure(iface)
